<?php

/**
 * @file
 * Contains fieldception.module.
 */

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function fieldception_theme() {
  $themes['fieldception_subfield'] = [
    'variables' => [
      'definition' => NULL,
      'label' => NULL,
      'label_display' => 'above',
      'content' => NULL,
      'attributes' => NULL,
      'title_attributes' => NULL,
      'content_attributes' => NULL,
      'tag' => 'div',
    ],
    'file' => 'fieldception.theme.inc',
  ];
  return $themes;
}

/**
 * Implements theme_preprocess_field_multiple_value_form().
 */
function fieldception_preprocess_field_multiple_value_form(&$variables) {
  if (isset($variables['element']['#fieldception_drag']) && empty($variables['element']['#fieldception_drag'])) {
    // Remove tabledrag if field is not set to be draggable.
    unset($variables['table']['#tabledrag']);
    unset($variables['table']['#header'][1]);
  }
}

/**
 * Implements hook_validation_constraint_alter().
 */
function fieldception_validation_constraint_alter(array &$definitions) {
  // This constraint is required to test empty boolean values.
  $definitions['NotEqualTo']['class'] = '\Symfony\Component\Validator\Constraints\NotEqualTo';
}
