<?php

/**
 * @file
 * Contains fieldception.module.
 */

/**
 * Implements hook_theme().
 */
function fieldception_theme() {
  $themes['fieldception_subfield'] = [
    'variables' => [
      'definition' => NULL,
      'label' => NULL,
      'label_display' => 'above',
      'content' => NULL,
      'attributes' => NULL,
      'title_attributes' => NULL,
      'content_attributes' => NULL,
    ],
    'file' => 'fieldception.theme.inc',
  ];
  return $themes;
}

/**
 * Implements theme_preprocess_field_multiple_value_form().
 */
function fieldception_preprocess_field_multiple_value_form(&$variables) {
  if (isset($variables['element']['#fieldception_drag']) && empty($variables['element']['#fieldception_drag'])) {
    // Remove tabledrag if field is not set to be draggable.
    unset($variables['table']['#tabledrag']);
    unset($variables['table']['#header'][1]);
  }
}
